version: "3"
services:
  prometheus:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - metrics
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: unless-stopped

networks:
  metrics:
    name: metrics
    external: true

volumes:
  grafana_storage: {}
