version: "3"
services:
  backend:
    container_name: backend
    image: healthylifestyle/backend:latest-test
    volumes:
      # - firebase_credentials:/temp
      - ./firebase-service-account.json:/temp/firebase-service-account.json
    # command: sh -c 'cp /firebase-service-account.json /temp'
    networks:
      - postgres
      - metrics
    environment:
      - PROFILE=${PROFILE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    expose:
      - 8085
    ports:
      - 8085:8085
    restart: unless-stopped

# volumes:
#   firebase_credentials:

networks:
  postgres:
    name: common
    external: true
  metrics:
    name: metrics
    external: true